version: "3.9"

services:

  app:
    build: .
    command: python3 /runner/cli.py
    volumes:
        - .:/project

  runner: 
    build: .
    command: >
        sh -c "pip install . &&
               runner ./samples/typos.yaml"
    volumes:
        - .:/app