version: "2.1"
services:
  openssh-server:
    image: ghcr.io/linuxserver/openssh-server
    container_name: openssh-server
    hostname: ssh-test-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=yonder-nomad-DECOY-rumba
      - USER_NAME=tricky
    ports:
      - 2222:2222
    restart: unless-stopped

  runner:
    depends_on: 
        - openssh-server
    image: trickytroll/good-bot-runner:latest
    container_name: good-bot-runner
    volumes:
        - .:/data
    environment:
        - SSH_TRICKY=yonder-nomad-DECOY-rumba
    command: runner /data/passwords.yaml
